Rscript -e "rmarkdown::render('Download_data.R')"

Rscript -e "rmarkdown::render('Exploratory_analyses.R')"

Rscript -e "rmarkdown::render('Statistical_analyses.R')"

Rscript -e "rmarkdown::render('Generate_figures.R')"

Rscript -e "rmarkdown::render('Gapminder_report.rmd')"